// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfjxbvsdgacrottucuqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmanhidnNkZ2Fjcm90dHVjdXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MjQzNjMsImV4cCI6MjA4NjMwMDM2M30.XqcCFHSc0rdUDl0S3ygBbHutArJ6yH7UGs_YX7i0_hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});